version: '3'

services:
  eventstore:
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    image: eventstore/eventstore:22.6.0-buster-slim
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - eventstore-volume-data:/var/lib/eventstore
      - eventstore-volume-logs:/var/log/eventstore

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-config:/data/configdb
      - mongo-data:/data/db

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express:latest
    ports:
      - 8081:8081
    restart: unless-stopped

  testing-eventstore:
    image: eventstore/eventstore:22.6.0-buster-slim
    environment:
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
    ports:
      - 11113:1113
      - 12113:2113

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongo-config:
  mongo-data:
